version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - restore_cache:
              keys:
                - v1-npm-deps-{{ checksum "package-lock.json" }}
                - v1-npm-deps-
            - run:
              name: Install dependencies
              command: npm i
            - save_cache:
              key: v1-npm-deps-{{ checksum "package-lock.json" }}
              paths:
                - ./node_modules
            - run:
              name: Jest test
              command: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test